Up to this point, we have explored using NumPy as a powerful library for implementing our primitives. However, data is not always provided in a matrix format; we often need to process it into that structure. A more practical and commonly encountered format is data stored in a CSV file.

For instance, let's look at the first few lines of Titanic data from the [Dataset](https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv).

```csv
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S
```

Apart from the non-numeric columns—which we’ll soon learn how to encode—each column has meaningful names. When working with this data, wouldn’t it be convenient to refer to fields by their names rather than their numerical indices? For instance, using the column name "Pclass" instead of referring to it as column 2.

[Pandas](https://pandas.pydata.org/) is a fantastic library for handling tabular data efficiently. Let’s explore a few examples. To start, let’s load the Titanic dataset into your notebook.

In [4]:
!curl https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv --output titanic.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
   458k      0 --:--:-- --:--:-- --:--:--  461k-:--:-- --:--:-- --:--:--     0

```!``` allows you to execute a command line code in a Jupyter lab cell. 


Downloading the dataset directly within the notebook is arguably the best approach, as it documents the source of the data and helps ensure the process leading to the final result is reproducible. Throughout the semester, we will likely discuss the importance of reproducible research.

You can take a quick look at the data using the following command:

In [5]:
!head titanic.csv

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26,0,0,STON/O2. 3101282,7.925,,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S
6,0,3,"Moran, Mr. James",male,,0,0,330877,8.4583,,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master Gosta Leonard",male,2,3,1,349909,21.075,,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,,S

In [6]:
!Get-Content titanic.csv -TotalCount 5

zsh:1: command not found: Get-Content

In [7]:
import pandas as pd
D = pd.read_csv("./titanic.csv")
D.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

you didn't really need to go though all those steps of downloading the data with curl and whatnot to get the data. I wanted to show you that so that you know how to get any data over an http connection. In reality, the following would work to load the data directly from github

In [8]:
D = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")
D.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

The first thing we’ll likely want to do with Pandas is extract subsets of the data. For instance, if we wanted to retrieve a single column, such as the passenger names, we can access it in a way similar to how we would retrieve data from a dictionary.

In [9]:
print(D["PassengerId"])

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [13]:
type(D["PassengerId"])

pandas.core.series.Series

Notice that although we've retrieved only one column, there are actually two columns of data. The first column (Index) contains the row numbers, while the second column contains the passenger names. We can use the row numbers to access specific rows. For example, to retrieve the 4th row, we can use the corresponding row number.

In [17]:
D["Name"][4]

'Allen, Mr. William Henry'

but, we will often want to get multiple columns, For example, imagine we wanted to get Name, Age, and if the passenger survived. We can get multiple columns with a standard python list:

In [18]:
D[["Name", "Age", "Ticket", "Survived"]]

,Name,Age,Ticket,Survived
0,"Braund, Mr. Owen Harris",22.0,A/5 21171,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,PC 17599,1
2,"Heikkinen, Miss Laina",26.0,STON/O2. 3101282,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,113803,1
4,"Allen, Mr. William Henry",35.0,373450,0
...,...,...,...,...
886,"Montvila, Rev. Juozas",27.0,211536,0
887,"Graham, Miss Margaret Edith",19.0,112053,1
888,"Johnston, Miss Catherine Helen ""Carrie""",NaN,W./C. 6607,0
889,"Behr, Mr. Karl Howell",26.0,111369,1
890,"Dooley, Mr. Patrick",32.0,370376,0

we will use tables and dataframes interchangeably. 

So, let's say you wanted to grab only the passengers that are over 20 years old. First, lets check out something super cool.

In [20]:
type(D["Age"])

pandas.core.series.Series

You can do the following as well.

In [19]:
D[["Age"]]

      Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

In [25]:
type(D[["Age"]])

pandas.core.frame.DataFrame

In [26]:
D["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [30]:
D["Age"].index

RangeIndex(start=0, stop=891, step=1)

In [43]:
type(D["Age"] > 20)

pandas.core.series.Series

In [44]:
D["Age"] > 15

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

That "series" of booleans has the same length as the number of rows. For any row where the age is greater than 20, it will be marked as True; otherwise, it will be False. This is already quite useful, but it gets even better. If we have a series of True and False values that matches the length of a DataFrame, we can easily retrieve any row where the value is True.

In [45]:
D[ D["Age"] > 25 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [46]:
D[ D["Pclass"] > 2 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q


This is arguably one of the most powerful and useful techniques for easily extracting subsets of data from a DataFrame. And it doesn't end there—you can create quite complex query criteria. In fact, for those familiar with SQL, many of the key relational algebra operations are implemented in the Pandas API. For more details, see the section on ["Comparison with SQL."](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html)

Additionally, if you just need a few entries of the data to experiment with, you can use:

What if you want to do the filtration for multiple columns at the same time?

In [10]:
mask = (D["Age"]>20) & (D["Pclass"]> 1)
mask
D[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

**Above is one method we could do this.**

There are other methods.

In [11]:
mask_series = pd.Series({"Age":20, "Pclass":1})
mask_series
subset = D[["Age", "Pclass"]]
subset[D[["Age", "Pclass"]] > mask_series] # you need to select the exact subset of the columns to pass the new mask.

      Age  Pclass
0    22.0     3.0
1    38.0     NaN
2    26.0     3.0
3    35.0     NaN
4    35.0     3.0
..    ...     ...
886  27.0     2.0
887   NaN     NaN
888   NaN     3.0
889  26.0     NaN
890  32.0     3.0

[891 rows x 2 columns]

In [12]:
D.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

to get the first 5 entries or specify the number that you want with

In [13]:
D.head(n=15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

Similarly you can get the last few lines with ```D.tail()```.

Note that sometimes, you may just want to make a data frame and not have a file to load in. In such a case, we can easily make one with the following code that builds a data frame of colors. (note that we mix strings and numbers)

In [16]:
D.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [25]:
df = pd.DataFrame([
    ['red', 255, 0, 0],
    ['blue', 0, 0, 255],
    ['green', 0, 255, 0],
    ['purple', 127, 0, 255],
])
df.columns=['name', 'R', 'G', 'B']
print(df)

     name    R    G    B
0     red  255    0    0
1    blue    0    0  255
2   green    0  255    0
3  purple  127    0  255

Outputting a DataFrame into a text file

A pandas DataFrame can be saved to a CSV file using the .to_csv() method. The arguments include the filename with path and index – where index = True implies writing the DataFrame’s index.

In [45]:
df.to_csv("test_data_out.csv", index=False)

Outputting a DataFrame into a text file

We can use to_csv function again, the only difference is the output file format is .txt, and you need to specify the separator using the **sep** arguement.

In [50]:
df.to_csv("test_data_out_text.txt", header=df.columns, index=None, sep = '\t')

The **.describe()** method prints the summary statistics of all numeric columns, such as count, mean, standard deviation, range, and quartiles of numeric columns.

In [52]:
print(df)
df.describe()

     name    R    G    B
0     red  255    0    0
1    blue    0    0  255
2   green    0  255    0
3  purple  127    0  255

                R       G           B
count    4.000000    4.00    4.000000
mean    95.500000   63.75  127.500000
std    122.028685  127.50  147.224319
min      0.000000    0.00    0.000000
25%      0.000000    0.00    0.000000
50%     63.500000    0.00  127.500000
75%    159.000000   63.75  255.000000
max    255.000000  255.00  255.000000

In [21]:
D.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In case you need to change the percentiles:

In [22]:
D.describe(percentiles=[0.3, 0.5, 0.7])

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
30%,268.000000,0.000000,2.000000,22.000000,0.000000,0.000000,8.050000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
70%,624.000000,1.000000,3.000000,36.000000,1.000000,0.000000,27.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

If you need to isolate specific data type in your summary, you can use the **include** arguement.

In [23]:
D.describe(include=[int])

       PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

Similarly, you might want to **exclude** certain data types using exclude argument.

In [53]:
D.describe(exclude=[int, float])

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [55]:
D.describe(exclude=[int, float]).T # takes the transpose of the matrix

         count unique                      top freq
Name       891    891  Braund, Mr. Owen Harris    1
Sex        891      2                     male  577
Ticket     891    681                   347082    7
Cabin      204    147                  B96 B98    4
Embarked   889      3                        S  644

You can use the function **info** to take a look at the data types, missing values, and shape of the dataframe.

In [63]:
D.info(show_counts=True, memory_usage=True, verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Number of rows and columns of the dataframe can be identified using the **.shape** attribute.

In [30]:
D.shape

(891, 12)

In [31]:
type(D.shape)

tuple

In [32]:
print(D.shape[0])
print(D.shape[1])

891
12

If you need to get the information about the column names, you can do this easily by:

In [33]:
D.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [34]:
D['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [76]:
titanic_copy = D.copy() # creates a SHALLOW COPY - doesn't make its own instance (deep copy)
titanic_deep_copy = D.copy(deep=True)
titanic_deep_copy.iloc[0,0] = 222222222
print(D==titanic_deep_copy)
titanic_copy.iloc[0,0] = 333333333
print(D==titanic_copy)

     PassengerId  Survived  Pclass  Name   Sex    Age  SibSp  Parch  Ticket  \
0          False      True    True  True  True   True   True   True    True
1           True      True    True  True  True   True   True   True    True
2           True      True    True  True  True   True   True   True    True
3           True      True    True  True  True   True   True   True    True
4           True      True    True  True  True   True   True   True    True
..           ...       ...     ...   ...   ...    ...    ...    ...     ...
886         True      True    True  True  True   True   True   True    True
887         True      True    True  True  True   True   True   True    True
888         True      True    True  True  True  False   True   True    True
889         True      True    True  True  True   True   True   True    True
890         True      True    True  True  True   True   True   True    True

     Fare  Cabin  Embarked
0    True  False      True
1    True   True      True
2    True  False      True
3    True   True      True
4    True  False      True
..    ...    ...       ...
886  True  False      True
887  True   True      True
888  True  False      True
889  True   True      True
890  True  False      True

[891 rows x 12 columns]
     PassengerId  Survived  Pclass  Name   Sex    Age  SibSp  Parch  Ticket  \
0          False      True    True  True  True   True   True   True    True
1           True      True    True  True  True   True   True   True    True
2           True      True    True  True  True   True   True   True    True
3           True      True    True  True  True   True   True   True    True
4           True      True    True  True  True   True   True   True    True
..           ...       ...     ...   ...   ...    ...    ...    ...     ...
886         True      True    True  True  True   True   True   True    True
887         True      True    True  True  True   True   True   True    True
888         True      True    True  True  True  False   True   True    True
889         True      True    True  True  True   True   True   True    True
890         True      True    True  True  True   True   True   True    True

     Fare  Cabin  Embarked
0    True  False      True
1    True   True      True
2    True  False      True
3    True   True      True
4    True  False      True
..    ...    ...       ...
886  True  False      True
887  True   True      True
888  True  False      True
889  True   True      True
890  True  False      True

[891 rows x 12 columns]

In [84]:
titanic_copy.head(7).isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
5,False,False,False,False,False,True,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False

In [85]:
titanic_copy.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

You can do a double sum to get the total number of nulls in the dataset.

In [90]:
titanic_copy.isnull().sum().sum()

np.int64(866)